[package]
name = "bevy-steamworks"
version = "0.9.0"
authors = ["james7132 <contact@jamessliu.com>"]
edition = "2021"
description = "A Bevy plugin for integrating with the Steamworks SDK."
repository = "https://github.com/james7132/bevy-steamworks"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "gamedev", "steam"]

[features]
default = []
serde = ["steamworks/serde"]

[dependencies]
bevy_log = "0.12"
bevy_app = "0.12"
bevy_ecs = "0.12"
bevy_utils = "0.12"
steamworks = { git = "https://github.com/Noxime/steamworks-rs", rev = "7b32b14" }

[dev-dependencies]
bevy = "0.12"
